
-- phpMyAdmin SQL Dump
-- version 3.5.2.2
-- http://www.phpmyadmin.net
--
-- 主机: localhost
-- 生成日期: 2018 年 01 月 21 日 10:13
-- 服务器版本: 10.1.21-MariaDB
-- PHP 版本: 5.2.17

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- 数据库: `u337031698_basic`
--

-- --------------------------------------------------------

--
-- 表的结构 `data`
--

CREATE TABLE IF NOT EXISTS `data` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Useraccount` varchar(30) COLLATE utf8_unicode_520_ci NOT NULL,
  `username` varchar(20) COLLATE utf8_unicode_520_ci NOT NULL,
  `Name` varchar(20) COLLATE utf8_unicode_520_ci NOT NULL,
  `Gender` varchar(1) COLLATE utf8_unicode_520_ci NOT NULL,
  `Birthday` date NOT NULL,
  `week` int(4) NOT NULL,
  `Parity` varchar(10) COLLATE utf8_unicode_520_ci NOT NULL,
  `weight` double NOT NULL,
  `BirthHeadWidth` double NOT NULL,
  `NowHeadWidth` double NOT NULL,
  `PerinatalInsult` text COLLATE utf8_unicode_520_ci NOT NULL,
  `Age` varchar(10) COLLATE utf8_unicode_520_ci NOT NULL,
  `Hasepilepsy` text COLLATE utf8_unicode_520_ci NOT NULL,
  `Diagnosis` varchar(80) COLLATE utf8_unicode_520_ci NOT NULL,
  `SeizureOnset` varchar(10) COLLATE utf8_unicode_520_ci NOT NULL,
  `InfantileSpasms` varchar(1) COLLATE utf8_unicode_520_ci NOT NULL,
  `HeatSpasm` varchar(1) COLLATE utf8_unicode_520_ci NOT NULL,
  `SeizureStatusWithFever` varchar(1) COLLATE utf8_unicode_520_ci NOT NULL,
  `SeizureClusterDuringFever` varchar(1) COLLATE utf8_unicode_520_ci NOT NULL,
  `GTC` varchar(1) COLLATE utf8_unicode_520_ci NOT NULL,
  `PartialSeizure` varchar(1) COLLATE utf8_unicode_520_ci NOT NULL,
  `TonicSpasms` varchar(1) COLLATE utf8_unicode_520_ci NOT NULL,
  `AbsenceSeizure` varchar(1) COLLATE utf8_unicode_520_ci NOT NULL,
  `BurstSupression` text COLLATE utf8_unicode_520_ci NOT NULL,
  `Hypsarrythmia` varchar(1) COLLATE utf8_unicode_520_ci NOT NULL,
  `3_6HzSpikeWaves` text COLLATE utf8_unicode_520_ci NOT NULL,
  `3HzSpikeWaves` text COLLATE utf8_unicode_520_ci NOT NULL,
  `SlowSpikeWaves` text COLLATE utf8_unicode_520_ci NOT NULL,
  `GeneralizedSeizure` varchar(1) COLLATE utf8_unicode_520_ci NOT NULL,
  `FocalSpikes` text COLLATE utf8_unicode_520_ci NOT NULL,
  `CerebralDysfunction` varchar(1) COLLATE utf8_unicode_520_ci NOT NULL,
  `UsedAntiepilepticDrugs` text COLLATE utf8_unicode_520_ci NOT NULL,
  `NowAntiepilepticDrugs` text COLLATE utf8_unicode_520_ci NOT NULL,
  `IntractableEpilepsy` varchar(1) COLLATE utf8_unicode_520_ci NOT NULL,
  `AutisticFeature` text COLLATE utf8_unicode_520_ci NOT NULL,
  `ADHD` varchar(1) COLLATE utf8_unicode_520_ci NOT NULL,
  `HandStereotype` text COLLATE utf8_unicode_520_ci NOT NULL,
  `AcquiredMicrocephaly` text COLLATE utf8_unicode_520_ci NOT NULL,
  `Hypotonia` text COLLATE utf8_unicode_520_ci NOT NULL,
  `Dysmorphysim` text COLLATE utf8_unicode_520_ci NOT NULL,
  `MR` varchar(20) COLLATE utf8_unicode_520_ci NOT NULL,
  `DD` varchar(20) COLLATE utf8_unicode_520_ci NOT NULL,
  `BrainCT` text COLLATE utf8_unicode_520_ci NOT NULL,
  `BrainMRI` text COLLATE utf8_unicode_520_ci NOT NULL,
  `SPECT` text COLLATE utf8_unicode_520_ci NOT NULL,
  `MetabolicExamination` text COLLATE utf8_unicode_520_ci NOT NULL,
  `CSF` text COLLATE utf8_unicode_520_ci NOT NULL,
  `LesionGene` text COLLATE utf8_unicode_520_ci NOT NULL,
  `Mutation` text COLLATE utf8_unicode_520_ci NOT NULL,
  `AAChange` text COLLATE utf8_unicode_520_ci NOT NULL,
  `NovelReported` text COLLATE utf8_unicode_520_ci NOT NULL,
  `Exon` text COLLATE utf8_unicode_520_ci NOT NULL,
  `DeNovo` text COLLATE utf8_unicode_520_ci NOT NULL,
  `Response` text COLLATE utf8_unicode_520_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_520_ci AUTO_INCREMENT=87 ;

--
-- 转存表中的数据 `data`
--

INSERT INTO `data` (`id`, `Useraccount`, `username`, `Name`, `Gender`, `Birthday`, `week`, `Parity`, `weight`, `BirthHeadWidth`, `NowHeadWidth`, `PerinatalInsult`, `Age`, `Hasepilepsy`, `Diagnosis`, `SeizureOnset`, `InfantileSpasms`, `HeatSpasm`, `SeizureStatusWithFever`, `SeizureClusterDuringFever`, `GTC`, `PartialSeizure`, `TonicSpasms`, `AbsenceSeizure`, `BurstSupression`, `Hypsarrythmia`, `3_6HzSpikeWaves`, `3HzSpikeWaves`, `SlowSpikeWaves`, `GeneralizedSeizure`, `FocalSpikes`, `CerebralDysfunction`, `UsedAntiepilepticDrugs`, `NowAntiepilepticDrugs`, `IntractableEpilepsy`, `AutisticFeature`, `ADHD`, `HandStereotype`, `AcquiredMicrocephaly`, `Hypotonia`, `Dysmorphysim`, `MR`, `DD`, `BrainCT`, `BrainMRI`, `SPECT`, `MetabolicExamination`, `CSF`, `LesionGene`, `Mutation`, `AAChange`, `NovelReported`, `Exon`, `DeNovo`, `Response`) VALUES
(51, 'jao59@hotmail.com', '梁昭鉉', '徐研晰', '男', '2008-07-29', 38, '1G1P', 3230, 34, 50, '無', '9歲4個月', '有，父親有FS', 'FS，ADHD', '1歲11個月', '無', '有', '有', '無', '有', '有', '無', '無', '無', '無', '無', '無', '無', '無', '無', '有', '無', 'Depakine，Keppra', '無', '無', '有', '無', '無', '無', '無', '無', '無', 'negative', 'negative', 'not performed', 'not performed', 'not performed', 'SCN1A', 'c.4555C>A', 'Pro1519Thr', '', '', 'paternal', 'father had FS'),
(50, 'hkpt0918@gmail.com', '測試人員', '小朋友', '女', '2016-10-10', 37, '1G1P', 3500, 25, 25, '無', '1歲0個月', '無', 'Autism', '0歲8個月', '無', '無', '', '無', '無', '無', '無', '無', '無', '無', '', '無', '無', '無', '', '無', 'Dilantin，Depakine', 'Lamictal，Sabril', '無', '無', '', '無', '無', '無', '無', 'mild', '走', '12', '12', '12', '12', '12', '12', '12', '12', '12', '12', '12', ''),
(60, 'flora1402@cgmh.org.tw', '洪碧蓮', '李宇恆', '男', '2011-07-12', 0, '0G0P', 0, 0, 0, '無', '6歲5個月', '無', 'Rolandic seizure，Developemental delay', '1歲0個月0天', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', 'Phenobarbital，Depakine，Trileptal，topamax，Keppra', 'Phenobarbital，topamax，Keppra', '無', '無', '無', '無', '無', '有', '無', '無', '無', '0', 'favor same lesion on left posterior parietal lobe', '0', '0', '0', 'No pathologic gene dosage variation was detected', '0', '0', ' (本內容僅供參考) 姓名：李宇恆                  病歷號碼：60555675     性別：男     年齡：6歲 病患來源：門診                                檢查日期：2017/10/26(四)                                               開單醫師：洪碧蓮 醫囑單號：76165661-17s0606006894   檔區：S     檢查項目：M29-018-Z　EEG (SLEEP) (小兒科)                              ---------------------------------------------------------------------- Sleep:     Recording condition:A 21-channel EEG obtained with the asleep patient .          Premedication: nil          Report:      1.The sleep record is not characterized by a background of mixed frequnecies         of medium amplitude delta waves and low amplitude fast activities.      2.Sleep spindles and vertex waves are noted.      3.Continous spikes and waves over left frontotemporal (F3T3)area was noted.          Interpretation:     This is an abnormal EEG during sleep.      Epileptic discharges are noted over left frontotemporal area.     This findings imply a localization-related epileptic disturbance.     Clinical-EEG correlation is required.          備註:     早產兒腦波檢查單開立時，請在開單註記欄寫上PCA AGE 為幾週，     以利報告判讀。               判讀主治醫師：洪碧蓮　                           2017/10/30    15:45:40', '0', '0', ''),
(61, 'flora1402@cgmh.org.tw', '洪碧蓮', '鄭圳佑', '男', '2015-12-20', 0, '0G0P', 4075, 0, 47, '無', '1歲11個月', '無', 'Developemental delay', '0歲4個月0天', '無', '無', '無', '無', '無', '無', '有', '無', '無', '無', '無', '無', '無', '有', '無', '無', 'Phenobarbital，Sabril，Keppra', 'Phenobarbital，Frisium', '無', '無', '無', '無', '無', '無', '無', '無', '無', '0', 'Relative hyperintense change of bilateral anterior temporal lobes', '0', '0', '0', '未發現PNPO 基因之突變點位', '0', '0', ' (本內容僅供參考) 姓名：鄭佑                  病歷號碼：5951676      性別：男     年齡：14個月 病患來源：門診                                檢查日期：2017/03/02(四)                                               開單醫師：洪碧蓮 醫囑單號：73190494-16s1122002120   檔區：S     檢查項目：M29-018-Z　EEG (SLEEP) (小兒科)                              ---------------------------------------------------------------------- Sleep:     Recording condition:A 21-channel EEG obtained with the asleep patient .          Premedication: nil          Report:      1.The sleep record is not characterized by a background of mixed frequnecies         of medium amplitude delta waves and low amplitude fast activities.      2.Sleep spindles and vertex waves are not noted.      3.Multifocal sharp waves was noted over various brain regions were noted.          Interpretation:     This is an abnormal EEG during sleep.      Epileptiform multifocal discharges are noted over various brain regions.     Clinical-EEG correlation is required.               判讀主治醫師：洪碧蓮　                           2017/03/03    09:58:03', '0', '0', ''),
(59, 'mingtao.yang.tw@gmail.com', '楊明道', '康喻凱', '男', '2015-10-01', 37, '1G1P', 3000, 40, 40, '無', '2歲1個月', '有，father', '無', '1歲0個月0天', '無', '無', '無', '無', '有', '無', '無', '無', '無', '無', '無', '無', '無', '無', '', '有', '無', 'Keppra', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', 'negative', '無', '無', '無', '', '', '', '', '', '', '已收檢體 尚未分析'),
(53, 'fieldof19@gmail.com', '余文豪', '蕭維德', '男', '2006-09-21', 38, '1G1P', 2950, 0, 0, '無', '11歲3個月', '無', 'EIEE', '0歲6個月', '有', '無', '無', '無', '有', '有', '有', '無', '有', '無', '', '無', '無', '有', '', '有', 'Depakine，Sabril', 'Trileptal，topamax，Keppra，Frisium', '有', '無', '無', '無', '有', '有', '無', '有，profound', '有，(bedridden)', 'Brain atrophy ', 'periventricular white matter hyperintensity (T2)', 'No survey', 'tandem mass:normal, UOA:Elevated 3-hydroxybutyric acid (ketosis-related??)', 'No survey', '', '', '', '', '', '', 'CDKL5	NM_003159.2:c.849dupT	NP_003150.1:p.Asp284Ter\nde novo \nseizure onset 是否為3m/o'),
(54, 'fieldof19@gmail.com', '余文豪', '郭秉勳 ', '男', '2015-08-12', 42, '1G1P', 2800, 0, 43, '有，susp brachial plexus and adrenal hemorrhage', '2歲3個月', '無', 'EIEE', '0歲1個月', '有', '無', '無', '無', '有', '有', '有', '無', '有', '無', '', '無', '無', '有', '', '有', '無', 'Phenobarbital，Depakine，Sabril，Keppra', '有', '無', '無', '無', '有', '有', '無', '有，profound', '有，(bedridden)', 'no survey ', 'brain MRI mild cerebral atrophy, negative MRS for glycien and lactate', 'no survey ', 'UOA:normal, Tandem mass:normal ', 'no survey ', '', '', '', '', '', '', 'K228 KBC 郭秉勳 ARX mutation NM_139058.2:c.1057C>T; NP_620689.1:p.Pro353Ser\n能否補送父母血確認'),
(55, 'fieldof19@gmail.com', '余文豪', '詹予臻', '女', '2015-05-10', 38, '1G1P', 2715, 32, 41, '無', '2歲6個月', '無', 'EIEE', '0歲0個月', '有', '無', '無', '無', '有', '有', '有', '無', '無', '無', '', '無', '無', '有', '', '有', 'Dilantin，其他，Rivotril', 'Phenobarbital，Trileptal，Frisium', '有', '無', '無', '無', '有', '有', '無', '有，severe', '有，(bedridden)', 'no survey ', 'Suspicious for migration disorder with thick gyri over frontal lobes and possibly polymicrogyria over parietooccipital lobes 2.Thin corpus callosum 3.hypomyelination ', 'no survey ', 'UOA:normal, Tandem mass:normal ', 'normal ', '', '', '', '', '', '', 'NGS　未檢出突變基因\nseizure onset 是幾天大?'),
(56, 'mingtao.yang.tw@gmail.com', '楊明道', '藍幼宸', '女', '2013-06-01', 38, '1G1P', 1, 1, 1, '無', '4歲6個月', '無', 'Developemental delay', '0歲9個月', '無', '無', '無', '有', '有', '有', '有', '無', '無', '無', '', '無', '無', '有', '', '有', 'Trileptal，topamax，Lamictal，Keppra', 'Depakine，Frisium，lacosamide', '有', '無', '無', '無', '無', '有', '無', '有，modereate', '有，坐', 'NA', 'negative', 'NA', 'NA', 'NA', '', '', '', '', '', '', 'NGS epilepsy panel 未檢出致病基因'),
(58, 'test', 'Test', '  ', '女', '2015-10-01', 22, '1G1P', 1000, 11, 11, '無', '2歲1個月', '無', 'West Syndrome，Lennox-Gastaut syndome，mental retardation', '0歲1個月0天', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '', '無', 'Neurontin，lacosamide', 'Tegretol，Sabril，Frisium', '無', '無', '無', '無', '無', '無', '無', '無', '無', '0', '0', '0', '0', '0', '', '', '', '', '', '', ''),
(62, 'flora1402@cgmh.org.tw', '洪碧蓮', '盧楀昊', '男', '2016-05-10', 40, '1G1P', 2495, 34, 45, '無', '1歲6個月', '無', 'Rolandic seizure', '0歲5個月0天', '無', '無', '無', '無', '無', '無', '有', '無', '無', '無', '無', '無', '無', '無', '無', '無', 'Depakine，topamax，Sabril，Keppra，生酮飲食', 'Depakine，topamax', '無', '無', '無', '無', '無', '無', '無', '無', '無', '0', 'Relative more prominent of left temporal horn compared with right.', '0', '0', 'normal', '0', '0', '0', ' (本內容僅供參考) 姓名：盧楀昊                  病歷號碼：5077611      性別：男     年齡：12個月 病患來源：住院         病 床 號：S07F0703A    檢查日期：2017/06/06(二)                                               開單醫師：洪碧蓮 醫囑單號：-178035255               檔區：S     檢查項目：M29-018-Z　EEG (SLEEP) (小兒科)                              ---------------------------------------------------------------------- Sleep:     Condition of recording:A 12-channel EEG obtained with the asleep patient .          Premedication: nil          Report:      1.The sleep record is not characterized by a background of medium amplitude      delta waves .      2.The more slow waves are noted.      3.There are scanty sleep spindles on both sides.      4.There is no asymmetry.          Interpretation:     This is an abnormal EEG during sleep shows slow background and scanty sleep      spindles.     These findings indicate cortical dysfunction.     Cranial MRI was suggested for further evaluation.          備註:     早產兒腦波檢查單開立時，請在開單註記欄寫上PCA AGE 為幾週，     以利報告判讀。               判讀主治醫師：洪碧蓮　                           2017/06/07    15:31:37', '0', '0', ''),
(63, 'flora1402@cgmh.org.tw', '洪碧蓮', '陳郡秀', '女', '2016-10-17', 38, 'G2P2', 3280, 0, 43, '無', '0歲6個月', '有，陳郡秀病童的曾祖母〈陳郡秀的父親的奶奶〉', 'Rolandic seizure', '1歲4個月0天', '無', '無', '無', '無', '無', '無', '有', '無', '無', '無', '無', '無', '無', '無', '無', '無', 'Phenobarbital，Depakine，Keppra', 'Depakine，Keppra', '無', '無', '無', '無', '無', '無', '無', '無', '無', '0', 'No definite active intracranial lesion.', '0', '0', '0', '未發現SCN1A 基因之突變點位', '0', '0', ' (本內容僅供參考) 姓名：陳郡秀                  病歷號碼：5961562      性別：女     年齡：7個月 病患來源：門診                                檢查日期：2017/05/25(四)                                               開單醫師：洪碧蓮 醫囑單號：75553748-17s0525006266   檔區：S     檢查項目：M29-018-Z　EEG (SLEEP) (小兒科)                              ---------------------------------------------------------------------- Sleep:     Recording condition:A 21-channel EEG obtained with the asleep patient .          Premedication: 10% Chloral hydrate Syrup(100mg/ml) 4 cc PO                          檢查結束: BP: 86/36mmHg. HR: 100/min. RR: 30/min. SaO2: 99%          Report:      1.The sleep record is not characterized by a background of mixed frequnecies         of medium amplitude delta waves and low amplitude fast activities.      2.Sleep spindles and vertex waves are noted.      3.Periodic sharp waves over right parietal area (P4) was noted.          Interpretation:     This is an abnormal EEG during sleep.      Epileptiform discharges are noted over right parietal area (P4).     This findings imply a localization-related epileptic disturbance.     Clinical-EEG correlation is required.          備註:     早產兒腦波檢查單開立時，請在開單註記欄寫上PCA AGE 為幾週，     以利報告判讀。   *** 第 1 次修改 ***              判讀主治醫師：洪碧蓮　                           2017/05/26    10:22:21', '0', '0', ''),
(64, 'flora1402@cgmh.org.tw', '洪碧蓮', '顏子袀', '男', '2010-01-14', 39, '2G1P', 3100, 32, 0, '無', '7歲11個月', '有，顏子袀病童的大姑姑〈顏子袀的父親的大姐〉', 'Rolandic seizure', '7歲3個月0天', '無', '無', '無', '無', '無', '無', '有', '無', '無', '無', '無', '無', '無', '無', '無', '無', '其他，diazepam', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '0', 'Suspicious focal high signal intensity change foci in left posterior insula.', '0', '0', '0', '0', '0', '0', '(本內容僅供參考) 姓名：顏子袀                  病歷號碼：5066005      性別：男     年齡：7歲 病患來源：住院         病 床 號：S07F0717A    檢查日期：2017/04/10(一)                                               開單醫師：陳垣舜 醫囑單號：29352626-178021460       檔區：S     檢查項目：M29-029-Z　EEG (AWAKE & SLEEP) (小兒科)                      ---------------------------------------------------------------------- Special Term:     Condition of recording:A 21-channel EEG obtained with the awake and asleep      patient      Premedication: nil     Report:      1.The awake tracing is characterized by symmetrical 9~10Hz posterior dominant         rhythm (approximately 25uV) which is reactive to eye opening and closure.      2.Lower amplitude fast activities are noted anteriorly.      3.Occasional posterior slow waves of youth are noted.      4.Hyperventilation lead to build-up of slowing activity.      5.Photic stimulation fails to activate the tracing.      6.There is a horizontal dipole of sharp and waves discharge.        Positive spikes over left frontal areas and simultaneous negative spikes         over left  centro-temporal areas with maximumat C3T3 are noted.      7.The sleep record enhances the abnormal findings noted in awake state.     Interpretation:      1.This is an abnormal EEG during wakefulness and sleep .        Epileptiform discharges of negativity over left centro-temporal areas and         positivity over left frontal areas are noted.      2.These findings are compatible with rolandic seizures.      3.Clinical-EEG correlation is required.               備註:     早產兒腦波檢查單開立時，請在開單註記欄寫上PCA AGE 為幾週，     以利報告判讀。                    判讀主治醫師：洪碧蓮　                           2017/04/12    10:14:57', '0', '0', ''),
(65, 'flora1402@cgmh.org.tw', '洪碧蓮', '陳君熙', '男', '2015-11-18', 32, '2G2P', 3250, 0, 42, '無', '2歲0個月', '無', 'Rolandic seizure', '1歲4個月0天', '無', '無', '無', '無', '無', '無', '有', '無', '無', '無', '無', '無', '無', '無', '無', '無', 'Phenobarbital，Sabril，Keppra，生酮飲食', 'Phenobarbital，Sabril', '無', '無', '無', '無', '無', '無', '無', '無', '無', '0', '1. General under development of whole brain 2. Hypoplasia of body and splenic of corpus callosum', '0', '0', 'sugar 79', 'Normal B-Hexosaminidase activity', '0', '0', ' (本內容僅供參考) 姓名：陳君熙                  病歷號碼：60748370     性別：男     年齡：16個月 病患來源：住院         病 床 號：S07F0719B    檢查日期：2017/04/11(二)                                               開單醫師：洪碧蓮 醫囑單號：29314302-178020186       檔區：S     檢查項目：M32-111　EEG MONITOR(DAY)                                    ---------------------------------------------------------------------- Awake and sleep:     Condition of recording:A 21-channel EEG obtained with the awake and asleep      patient      Premedication: nil          Report:      1.The awake tracing is characterized by symmetrical 9~10Hz posterior dominant         rhythm (approximately 25uV) which is reactive to eye opening and closure.      2.Lower amplitude fast activities are noted anteriorly.      3.Occasional posterior slow waves of youth are noted.      4.Hyperventilation lead to build-up of slowing activity.      5.Photic stimulation fails to activate the tracing.      6.Continous slow waves was noted over left occipital area (O1).      7.The sleep record did not enhance the abnormal findings noted in the awake      state.      8.The sleep  background of mixed frequnencies of medium amplitude         delta waves and low amplitude fast activities.      9.Sleep spindles and vertex waves are noted.          Interpretation:      1.This is an abnormal EEG during wakefulness and sleep demonstrate epileptiform      discharge over left occipital area.      2.Clinical-EEG correlation is required.          備註:     早產兒腦波檢查單開立時，請在開單註記欄寫上PCA AGE 為幾週，     以利報告判讀。                         判讀主治醫師：洪碧蓮　                           2017/04/12    10:11:26', '0', '0', ''),
(66, 'flora1402@cgmh.org.tw', '洪碧蓮', '馬霈萱', '女', '2014-11-03', 39, '1G1P', 3000, 0, 0, '無', '3歲0個月', '有，馬霈萱病童的外曾祖母〈馬霈萱的母親的外婆〉', 'Rolandic seizure', '2歲4個月0天', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '有', '無', '無', 'Keppra', 'Keppra', '無', '無', '無', '無', '無', '無', '無', '無', '無', '1. No significant focal brain lesion 2. No evidence of recent intracranial hemorrhage.', '0', '0', '0', '0', '0', '0', '0', ' (本內容僅供參考) 姓名：馬霈萱                  病歷號碼：60695627     性別：女     年齡：2歲 病患來源：住院         病 床 號：S07F0722A    檢查日期：2017/04/25(二)                                               開單醫師：陳泊儒 醫囑單號：29554620-178025263       檔區：S     檢查項目：M29-018-Z　EEG (SLEEP) (小兒科)                              ---------------------------------------------------------------------- Sleep:     This EEG examination included sleep record.          Premedication: 10% Chloral hydrate Syrup(100mg/ml) 6.5 cc PO                          檢查結束: BP: 89/50mmHg. HR: 99/min. RR: 25/min. SaO2:100 %          The sleep record showed diffuse irregular 5-6 Hz,25-50 uV      activity mixed with low voltage fast activity over both      hemispheres. The record was symmetric.There were bilateral      synchronous sleep spindles and vertex sharp wave over      central areas. No focal epileptiform or slow activity      was found.          Conclusion:  Negative record.          備註:     早產兒腦波檢查單開立時，請在開單註記欄寫上PCA AGE 為幾週，     以利報告判讀。                       By Pi-Lien Hung M.D.   *** 第 1 次修改 ***              判讀主治醫師：洪碧蓮　                           2017/04/26    12:04:47', '0', '0', ''),
(67, 'flora1402@cgmh.org.tw', '洪碧蓮', '劉耘希', '女', '2011-09-04', 0, '0G0P', 0, 0, 49, '無', '6歲3個月', '無', 'Rolandic seizure', '1歲4個月0天', '無', '無', '無', '有', '無', '無', '有', '無', '無', '無', '無', '無', '無', '無', '無', '無', 'Phenobarbital', 'Phenobarbital', '無', '無', '無', '無', '無', '無', '無', '無', '無', '0', 'Unremarkable finding of presence study', '0', '0', '0', '0', '0', '0', ' (本內容僅供參考) 姓名：劉耘希                  病歷號碼：5885322      性別：女     年齡：5歲 病患來源：門診                                檢查日期：2017/01/12(四)                                               開單醫師：洪碧蓮 醫囑單號：72431582-16s1030000014   檔區：S     檢查項目：M29-029-Z　EEG (AWAKE & SLEEP) (小兒科)                      ---------------------------------------------------------------------- Awake and sleep:     Condition of recording:A 21-channel EEG obtained with the awake and asleep      patient      Premedication: nil     Report:      1.The awake tracing is characterized by symmetrical 9~10Hz posterior dominant         rhythm (approximately 25uV) which is reactive to eye opening and closure.      2.Lower amplitude fast activities are noted anteriorly.      3.Occasional posterior slow waves of youth are noted.      4.Hyperventilation lead to build-up of slowing activity.      5.Photic stimulation fails to activate the tracing.      6.Focal sharp waves with left centro-temporal predominance       7.The sleep record did not enhance the abnormal findings noted in the awake      state.      8.The sleep  background of mixed frequnencies of medium amplitude         delta waves and low amplitude fast activities.      9.Sleep spindles and vertex waves are noted.          Interpretation:      1.This is an abnormal EEG during wakefulness and sleep demonstrate epileptic      discharge over left centro-temporal area.      2.Clinical-EEG correlation is required.                    判讀主治醫師：洪碧蓮　                           2017/01/13    12:07:16', '0', '0', ''),
(68, 'flora1402@cgmh.org.tw', '洪碧蓮', '黃嘉興', '男', '2013-06-06', 0, '1G1P', 3465, 0, 0, '無', '4歲6個月', '有，黃嘉興病童的小阿姨在18歲時有車禍後產生癲癇。', 'Developemental delay', '3歲11個月0天', '無', '無', '無', '無', '無', '無', '有', '無', '無', '無', '無', '無', '無', '無', '無', '無', 'Phenobarbital，Keppra，其他，l-carnitine', 'Keppra', '無', '無', '無', '無', '無', '無', '無', '無', '無', '0', 'Stationary of bilateral thalamus hyperintense change', '0', '0', '0', '不具有脊髓性肌肉萎縮症SMN1 基因缺失', '0', '0', '(本內容僅供參考) 姓名：黃嘉興                  病歷號碼：60619903     性別：男     年齡：3歲 病患來源：門診                                檢查日期：2017/04/25(二)                                               開單醫師：洪碧蓮 醫囑單號：73624726-16s1108004107   檔區：S     檢查項目：M29-018-Z　EEG (SLEEP) (小兒科)                              ---------------------------------------------------------------------- Sleep:     Recording condition:A 21-channel EEG obtained with the asleep patient .          Premedication: 10% Chloral hydrate Syrup(100mg/ml) 7 cc PO                          檢查結束: BP: 81/38mmHg. HR: 87/min. RR: 24/min. SaO2: 94%          Report:      1.The sleep record is not characterized by a background of mixed frequnecies         of medium amplitude delta waves and low amplitude fast activities.      2.Sleep spindles and vertex waves are noted.      3.Periodic sharp waves over left frontotemporal area was noted.          Interpretation:     This is an abnormal EEG during sleep.      Epileptic discharges are noted over left frontotemporal area.     This findings imply a localization-related epileptic disturbance.     Clinical-EEG correlation is required.          備註:     早產兒腦波檢查單開立時，請在開單註記欄寫上PCA AGE 為幾週，     以利報告判讀。   *** 第 1 次修改 ***              判讀主治醫師：洪碧蓮　                           2017/04/26    12:04:11', '0', '0', ''),
(69, 'flora1402@cgmh.org.tw', '洪碧蓮', '許硯程', '男', '2008-12-17', 0, '0G0P', 0, 0, 0, '無', '9歲0個月', '無', 'Rolandic seizure', '1歲10個月0天', '無', '無', '無', '無', '有', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', 'Depakine，Keppra，生酮飲食', 'Depakine，Keppra', '無', '無', '無', '無', '無', '無', '無', '無', '無', '0', 'No definite active intracranial lesion.', '0', '0', 'normal', '0', '0', '0', ' (本內容僅供參考) 姓名：許硯程                  病歷號碼：5851153      性別：男     年齡：8歲 病患來源：門診                                檢查日期：2017/05/18(四)                                               開單醫師：洪碧蓮 醫囑單號：74608823-17s0224006261   檔區：S     檢查項目：M29-029-Z　EEG (AWAKE & SLEEP) (小兒科)                      ---------------------------------------------------------------------- Awake and sleep:     Condition of recording:A 21-channel EEG obtained with the awake and asleep      patient           Premedication: 10% Chloral hydrate Syrup(100mg/ml) 12 cc PO                          檢查結束: BP: 97/59mmHg. HR: 75/min. RR: 30/min. SaO2: 95%          Report:      1.The awake tracing is not characterized by symmetrical 9~10Hz posterior      dominant         rhythm (approximately 25uV) which is reactive to eye opening and closure.      2.Lower amplitude fast activities are noted anteriorly.      3.Occasional posterior slow waves of youth are noted.      4.Hyperventilation lead to build-up of slowing activity.      5.Photic stimulation fails to activate the tracing.      6.Focal sharp waves with left frontal predominance(F7)      7.The sleep record did not enhance the abnormal findings noted in the awake      state.      8.The sleep  background of mixed frequnencies of medium amplitude         delta waves and low amplitude fast activities.      9.Sleep spindles and vertex waves are noted.          Interpretation:      1.This is an abnormal EEG during wakefulness and sleep demonstrate epileptic              discharge over left frontal area.      2.Clinical-EEG correlation is required.          備註:     早產兒腦波檢查單開立時，請在開單註記欄寫上PCA AGE 為幾週，     以利報告判讀。             *** 第 1 次修改 ***              判讀主治醫師：洪碧蓮　                           2017/05/19    11:15:16', '0', '0', ''),
(70, 'flora1402@cgmh.org.tw', '洪碧蓮', '王正雄', '男', '2010-09-24', 0, '0G0P', 0, 0, 0, '無', '7歲3個月', '有，王正雄病童的舅公(媽媽的叔叔)', 'Rolandic seizure', '3歲11個月0天', '無', '無', '無', '無', '有', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', 'Phenobarbital，Trileptal，Lamictal，Keppra', 'Trileptal，Lamictal', '無', '無', '無', '無', '無', '無', '無', '無', '無', '0', 'Favor right medial temporal lobe epilepsy', '0', '0', '0', '0', '0', '0', ' (本內容僅供參考) 姓名：王正雄                  病歷號碼：5918906      性別：男     年齡：6歲 病患來源：門診                                檢查日期：2017/07/25(二)                                               開單醫師：洪碧蓮 醫囑單號：74844420-17s0314001149   檔區：S     檢查項目：M29-018-Z　EEG (SLEEP) (小兒科)                              ---------------------------------------------------------------------- Sleep:     Recording condition:A 21-channel EEG obtained with the asleep patient .          Premedication:nil     Report:      1.The sleep record is not characterized by a background of mixed frequnecies         of medium amplitude delta waves and low amplitude fast activities.      2.Sleep spindles and vertex waves are not noted.      3.Periodic unsynchronized spikes over bilateral frontal area was noted.          Interpretation:     This is an abnormal EEG during sleep.      Epileptic discharges are noted over bilateral frontal area.     Clinical-EEG correlation is required.          備註:     早產兒腦波檢查單開立時，請在開單註記欄寫上PCA AGE 為幾週，     以利報告判讀。               判讀主治醫師：洪碧蓮　                           2017/08/01    17:23:52', '0', '0', ''),
(71, 'flora1402@cgmh.org.tw', '洪碧蓮', '鄭博遠', '男', '2014-03-03', 38, '1G1P', 3290, 0, 0, '無', '3歲9個月', '有，爸爸睡覺時不自覺踢腳', 'Rolandic seizure', '0歲10個月0天', '無', '無', '無', '有', '有', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', 'Depakine', 'Depakine', '無', '無', '無', '無', '無', '無', '無', '無', '無', '0', 'Focal small cortical hyperintense change in left mesial temporal lobe on long TR Abnormal gyral patterns with cortical thickening in right medial parietal lobe', '0', '0', '0', '0', '0', '0', ' (本內容僅供參考) 姓名：鄭博遠                  病歷號碼：5925704      性別：男     年齡：3歲 病患來源：住院         病 床 號：S07G0772B    檢查日期：2017/06/07(三)                                               開單醫師：謝馨儀 醫囑單號：30072201-178035218       檔區：S     檢查項目：M29-018-Z　EEG (SLEEP) (小兒科)                              ---------------------------------------------------------------------- Sleep:     Recording condition:A 21-channel EEG obtained with the asleep patient .          Premedication: nil          Report:      1.The sleep record is characterized by a background of mixed frequnecies         of medium amplitude delta waves and low amplitude fast activities.      2.Sleep spindles and vertex waves are noted.      3.Focal sharp waves over right parietal area (P4) area was noted.          Interpretation:     This is an abnormal EEG during sleep.      Epileptiform discharges are noted over right parietal area.     This findings imply a localization-related epileptic disturbance.     Clinical-EEG correlation is required.          備註:     早產兒腦波檢查單開立時，請在開單註記欄寫上PCA AGE 為幾週，     以利報告判讀。               判讀主治醫師：洪碧蓮　                           2017/06/09    09:29:32', '0', '0', ''),
(72, 'flora1402@cgmh.org.tw', '洪碧蓮', '黃翔威', '男', '2014-10-23', 38, '1G1P', 4590, 0, 49, '無', '3歲1個月', '無', 'Developemental delay', '2歲8個月0天', '無', '無', '無', '無', '有', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', 'Depakine', 'Depakine', '無', '無', '無', '無', '無', '無', '無', '無', '無', '0', 'Suspicious minimal cortical hyperintence change in bilateral high medial frontal lobe?', '0', '0', '0', '0', '0', '0', ' (本內容僅供參考) 姓名：黃翔威                  病歷號碼：5921482      性別：男     年齡：2歲 病患來源：住院         病 床 號：S06G0651C    檢查日期：2017/06/08(四)                                               開單醫師：謝馨儀 醫囑單號：30086675-178035457       檔區：S     檢查項目：M29-018-Z　EEG (SLEEP) (小兒科)                              ---------------------------------------------------------------------- Sleep:     Recording condition:A 21-channel EEG obtained with the asleep patient .          Premedication: nil          Report:      1.The sleep record is not characterized by a background of mixed frequnecies         of medium amplitude delta waves and low amplitude fast activities.      2.Sleep spindles and vertex waves are noted.      3.Nultifocal high voltage sharp waves and spikes were noted.          Interpretation:     This is an abnormal EEG during sleep.      Multifocal epileptiform discharges are noted.     This findings imply a localization-related epileptic disturbance.     Clinical-EEG correlation is required.          備註:     早產兒腦波檢查單開立時，請在開單註記欄寫上PCA AGE 為幾週，     以利報告判讀。               判讀主治醫師：洪碧蓮　                           2017/06/09    09:25:03', '0', '0', ''),
(73, 'flora1402@cgmh.org.tw', '洪碧蓮', '凃楷紘', '男', '2011-05-06', 0, '0G0P', 0, 0, 0, '無', '6歲7個月', '無', 'Rolandic seizure', '0歲6個月0天', '無', '無', '無', '無', '有', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', 'Phenobarbital，Depakine', 'Depakine', '無', '無', '無', '無', '無', '無', '無', '無', '無', '0', 'Unremarkable finding of presence study', '0', '0', '0', '0', '0', '0', '(本內容僅供參考) 姓名：楷紘                  病歷號碼：5872332      性別：男     年齡：6歲 病患來源：住院         病 床 號：S06G0659A    檢查日期：2017/06/26(一)                                               開單醫師：洪碧蓮 醫囑單號：30307641-178039089       檔區：S     檢查項目：M29-018-Z　EEG (SLEEP) (小兒科)                              ---------------------------------------------------------------------- Sleep:     Condition of recording:A 12-channel EEG obtained with the asleep patient .          Premedication: nil          Report:      1.The sleep record is not characterized by a background of medium amplitude      delta waves .      2.The more slow waves are noted.      3.There are scanty sleep spindles on sides.      4.There is no asymmetry.          Interpretation:     This is an abnormal EEG during sleep shows slow background and scanty sleep      spindles.     The record is no asymmetric.     These findings indicate cortical dysfunction.     Cranial MRI was suggested for further evaluation.          備註:     早產兒腦波檢查單開立時，請在開單註記欄寫上PCA AGE 為幾週，     以利報告判讀。               判讀主治醫師：洪碧蓮　                           2017/06/27    15:05:31', '0', '0', ''),
(74, 'flora1402@cgmh.org.tw', '洪碧蓮', '黃乙元', '男', '2013-09-18', 0, '0G0P', 0, 0, 0, '無', '4歲2個月', '有，爸爸兒時曾高燒後抽搐', 'Developemental delay', '0歲10個月0天', '無', '無', '無', '有', '有', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', 'Phenobarbital，Depakine，Keppra', 'Depakine', '無', '無', '無', '無', '無', '無', '無', '無', '無', 'No evidence of intracranial hemorrhage', 'Essential unremarkable study', '0', '0', 'WBC:1 RBC:18 NEUTROPHIL:100%', '0', '0', '0', ' (本內容僅供參考) 姓名：黃乙元                  病歷號碼：5916071      性別：男     年齡：3歲 病患來源：門診                                檢查日期：2016/12/14(三)                                               開單醫師：洪碧蓮 醫囑單號：71291097-16s0621003862   檔區：S     檢查項目：M29-018-Z　EEG (SLEEP) (小兒科)                              ---------------------------------------------------------------------- Sleep:     This EEG examination included sleep record.          Premedication: 10% Chloral hydrate Syrup(100mg/ml) 7 cc PO                         檢查結束:  HR: 102/min. RR: 26/min. SaO2:96 %          The sleep record showed diffuse irregular 5-6 Hz,25-50 uV      activity mixed with low voltage fast activity over both      hemispheres. The record was symmetric.There were bilateral      synchronous sleep spindles and vertex sharp wave over      central areas. No focal epileptiform or slow activity      was found.          Conclusion:  Negative record.                       By Pi-Lien Hung M.D.   *** 第 1 次修改 ***              判讀主治醫師：洪碧蓮　                           2016/12/14    16:19:40', '0', '0', ''),
(75, 'flora1402@cgmh.org.tw', '洪碧蓮', '陳致翔', '男', '2000-01-29', 0, '0G0P', 0, 0, 0, '無', '18歲0個月', '無', 'Rolandic seizure', '17歲4個月0天', '無', '無', '無', '無', '有', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', 'Depakine', 'Depakine', '無', '無', '無', '無', '無', '無', '無', '無', '無', 'No evidence of intracranial hemorrhage', 'Essential unremarkable finding in this study', '0', '0', '0', '0', '0', '0', '(本內容僅供參考) 姓名：陳致翔                  病歷號碼：5628858      性別：男     年齡：17歲 病患來源：住院         病 床 號：S05A0519A    檢查日期：2017/05/23(二)                                               開單醫師：賴向榮 醫囑單號：29906557-178031484       檔區：SG    檢查項目：M29-018　EEG (SLEEP)                                         ---------------------------------------------------------------------- Data:     Type of recording: Routine      Condition: Awake      Artifacts: Rare      Clinical diagnosis:  Screening for cerebral cortical function          I.EEG diagnosis:         Normal          II.EEG description:      1. Background activities:         Alpha: 9-10 HZ, 20-60 UV, symmetry +; amount large                         blocked by eye opening +          Beta: 18-20 HZ, 5-10 UV, symmetry +; reactivity +; amount large      2. Abnormal activity          None       3. Epileptiform activity          None      4. Ictal activity          None      5. Hyperventilation: not done         Build up: none      6. Photic stimulation: not done, -          III.Interpretation:        No evidence of cerebral cortical dysfunction             IV.Recommendation:         Neurologic check-up         -               判讀主治醫師：陳乃菁　                           2017/05/24    12:34:35', '0', '0', ''),
(76, 't', 't', 't', '男', '2017-11-22', 1, '1G1P', 1, 1, 1, '無', '0歲0個月', '無', 'Autism', '1歲1個月1天', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', 'Lt frontal，Lt temporal，Lt parietal', '無', 'Trileptal，topamax，Lamictal，Sabril', 'Keppra，Frisium', '無', '無', '無', '無', '無', '無', '無', '無', '無', '1', '1', '1', '1', '1', '1', '', '', '', '', '', ''),
(77, 't', 't', 'w', '女', '2017-11-15', 1, '1G1P', 1, 1, 1, '無', '0歲0個月', '無', '無', '3歲3個月3天', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', 'Lt occipital，Rt frontal', '無', 'Depakine，Trileptal，topamax，Lamictal，Sabril，Lyrica，Neurontin，Keppra，Frisium', 'topamax，Lamictal，Sabril，Lyrica', '無', '無', '無', '無', '無', '無', '無', '無', '無', '2', '23', '23', '32', '23', '23', '', '', '', '', '', ''),
(78, 'mingtao.yang.tw@gmail.com', '楊明道', '張賀銘', '男', '2005-11-19', 37, '0G0P', 0, 0, 0, '無', '12歲2個月', '有，FS', 'FS，mental retardation，ADHD', '11歲4個月0天', '無', '有', '無', '無', '有', '無', '無', '無', '無', '無', '無', '無', '無', '無', 'Lt frontal', '無', '無', 'Keppra', '無', '無', '有', '無', '無', '無', '無', '有，mild', '無', 'NA', 'NA', 'NA', 'NA', 'NA', '', '', '', '', '', '', 'TBC1D24 mutation 需進一步確認\n'),
(79, 'flora1402@cgmh.org.tw', '洪碧蓮', '鄭權敏', '男', '2001-11-13', 0, '0G0P', 0, 0, 0, '無', '16歲3個月', '無', '無', '14歲0個月0天', '無', '無', '無', '無', '有', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', 'Depakine', 'Depakine', '無', '無', '無', '無', '無', '無', '無', '無', '無', 'No evidence of intracranial hemorrhage', 'No evident abnormal hyperintense change in bilateral hippocampus or right frontal lobe.', '0', '0', '0', '0', '0', '0', '0', '0', 'EEG revealed abnormal EEG during wakefulness and sleep demonstrate epileptic discharge over right frontal area with extending into bilateral frontal area.', '鄭權敏 NM_004366.5:c.817C>T; NP_004357.3:p.Arg273Trp\n能否送父母的血\n並將基本資料填完整 (EEG finding 是否填錯?)'),
(80, 'jao59@hotmail.com', '梁昭鉉', '林姿伶', '女', '2007-03-20', 38, '2G2P', 2980, 0, 0, '無', '10歲10個月', '有，媽媽和姐姐', '其他，Speech delay, inattention', '0歲0個月3天', '無', '無', '無', '無', '有', '無', '無', '有', '無', '無', '無', '無', '無', '無', 'Rt frontal，Rt temporal', '無', '無', 'Depakine', '無', '無', '無', '無', '無', '無', '無', '有，mild', '無', 'not performed', 'negative', 'not performed', 'not performed', 'not performed', 'KCNQ2', '', '', '', '', 'mother ', 'seizure type 臉脹紅眼上吊> generalized tonic seizure\nsister seizure onset 2 w/o\nmother:0928896619'),
(81, 'mingtao.yang.tw@gmail.com', '楊明道', '王心伶', '女', '2010-07-02', 0, '0G0P', 0, 0, 0, '無', '7歲6個月', '有，father', 'Rolandic seizure', '6歲0個月0天', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', '無', 'Lt temporal', '無', '無', 'Keppra', '無', '無', '有', '無', '無', '無', '無', '無', '無', 'NA', 'negative', 'NA', 'NA', 'NA', '', '', '', '', '', '', 'DNM1 mutation, 需進一步確認\n'),
(82, 'jao59@hotmail.com', '梁昭鉉', '周子堯', '男', '2009-05-10', 38, '2G2P', 2460, 32, 46, '無', '8歲8個月', '無', 'EE，Autism，mental retardation，Developemental delay', '1歲2個月0天', '無', '無', '無', '無', '有', '有', '無', '無', '無', '無', '無', '無', '無', '有', 'Lt temporal，Rt temporal', '無', 'Trileptal，Keppra', 'topamax，其他，vit B and Q10', '無', '有', '無', '無', '無', '無', '無', '有，profound', '有，走', 'negative', 'negative', 'not performed', 'not performed', 'not performed', '', '', '', '', '', '', ''),
(83, 'mingtao.yang.tw@gmail.com', '楊明道', '林秉璁（林煥星)', '男', '2008-08-09', 0, '0G0P', 0, 0, 0, '無', '9歲6個月', '無', 'mental retardation', '0歲0個月2天', '無', '無', '無', '無', '有', '有', '無', '無', '無', '無', '有', '有', '有', '有', 'Lt frontal，Lt temporal', '有', 'Phenobarbital，Depakine，Trileptal，Lamictal，其他，Rivotril', 'Keppra，Frisium，lacosamide', '有', '無', '有', '無', '無', '無', '無', '有，modereate', '無', 'NA', 'PVL?', 'NA', 'NA', 'NA', '', '', '', '', '', '', 'ADGRV1 mutation \n'),
(84, 'mingtao.yang.tw@gmail.com', '楊明道', '鄭承志', '男', '2006-03-20', 0, '0G0P', 0, 0, 0, '無', '11歲11個月', '有，maternal family', '無', '11歲5個月0天', '無', '無', '無', '無', '無', '有', '無', '無', '無', '無', '無', '無', '無', '無', 'Rt frontal，Rt parietal', '無', '無', 'Trileptal', '無', '無', '無', '無', '無', '無', '無', '無', '無', 'NA', 'negative', 'NA', 'NA', 'NA', '', '', '', '', '', '', ''),
(85, 'jao59@hotmail.com', '梁昭鉉', '陳愷隆', '男', '1994-12-13', 38, '2G2P', 3200, 0, 0, '無', '23歲5個月', '無', '其他，FIQ72,hepatitis,', '1歲2個月0天', '無', '有', '無', '有', '有', '有', '無', '無', '無', '無', '無', '無', '無', '無', 'Lt frontal，Rt frontal', '無', 'Trileptal', 'Keppra', '無', '無', '無', '無', '無', '有', '無', '有，mild', '有，走', 'not performed', 'not performed', 'not performed', 'not performed', 'not performed', 'PCDH19', 'c.617T>G', 'p.Phe206Cys', 'unknown', 'unknowm', 'yes', ''),
(86, 'jao59@hotmail.com', '梁昭鉉', '劉芝秀', '女', '1997-11-07', 40, '2G2P', 3000, 0, 0, '無', '20歲5個月', '無', 'EE，Autism，FS，mental retardation，Developemental delay', '1歲0個月0天', '無', '有', '有', '有', '有', '有', '無', '無', '無', '無', '無', '無', '無', '無', 'Rt frontal，Rt temporal', '有', 'Dilantin，Phenobarbital，Depakine，Trileptal', 'Sabril', '有', '有', '有', '無', '無', '無', '無', '有，modereate', '有，走', 'negative', 'negative', 'hypoperfusion at left frontal and right temporal-occipital junction ', 'not performed', 'negative', 'PCDH19', '0', '0', '0', '0', 'not maternal ', '');

-- --------------------------------------------------------

--
-- 表的结构 `user`
--

CREATE TABLE IF NOT EXISTS `user` (
  `Account` varchar(30) COLLATE utf8_unicode_520_ci NOT NULL,
  `Pwd` varchar(32) COLLATE utf8_unicode_520_ci NOT NULL,
  `Name` varchar(30) COLLATE utf8_unicode_520_ci NOT NULL,
  `Phone` varchar(20) COLLATE utf8_unicode_520_ci NOT NULL,
  `Hospital` varchar(20) COLLATE utf8_unicode_520_ci NOT NULL,
  PRIMARY KEY (`Account`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_520_ci;

--
-- 转存表中的数据 `user`
--

INSERT INTO `user` (`Account`, `Pwd`, `Name`, `Phone`, `Hospital`) VALUES
('fieldof19@gmail.com', 'd7a986478f64567130294dffb6cf3053', '余文豪', '0912160155', '成大醫院'),
('flora1402@cgmh.org.tw', 'dc597e215f6f92f5336cef14b49b1bec', '洪碧蓮', '0975056196', '高長'),
('pcfan6@ntu.edu.tw', 'c08053bec5c2896958f135a182c7ff9d', '范碧娟', '0972651824', '台大醫院'),
('i528528528', 'e1be323ed1bc4d3f7702ddceaf70d666', '李英齊', '0953613690', '中山附醫'),
('mingtao.yang.tw@gmail.com', 'bcbc75598b25e22c4a7e5425d87d1413', '楊明道', '0932220405', '亞東醫院'),
('jao59@hotmail.com', '0247e083c5262bd13611adce0f216041', '梁昭鉉', '0928520688', '亞東醫院'),
('test', '098f6bcd4621d373cade4e832627b4f6', 'Test', '', ''),
('minlan456@hotmail.com', '97628afafd75d9ea44ca4bf3acd58f45', '蔡明蘭', '0975100290', '北醫'),
('mantour.tw@gmail.com', '0cda704b4b5ed4238ae0d4ff1924fa50', '彥儒', '0912885800', '台大醫院');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
